name: Checkov

on:
  pull_request:
    branches: ["main"]
    paths:
      - "terraform/*"
      - "files/*"

jobs:
  Checkov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform,all
